name: tws ci workflow
on:
  push:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
     -name: checkout code 
     uses: actions/checkout@v4

     -name: Setup Docker
     uses: docker/setup-buildx-action@v4